on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-for-windows:
    name: Build Windows
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v3

      - name: Install .NET workloads
        run: dotnet workload install maui-windows

      - name: Compile
        run: dotnet build ZeroV.Desktop.slnf --configuration Debug
